### ISSUE TITLE
Theme is always random

### ISSUE THREAD

**Issue by jcd92** [mrf345/flask_datepicker#3]
Hi,
it seems your last change to the code that handles random theme selection and memory of that setting has resulted in always getting a random value.  This is because if you don't disable random_remember then it runs choice(themes).  The only alternative is it just sets self.random_theme, which will be None on the first iteration, and doesn't get updated with the value supplied in loader()

**Comment by mrf345** [comment]
Hello,
Thanks for the report and the assessment.
It seems I did a terrible thinko in one of the recent commits. I'm on it.

**Comment by mrf345** [comment]
@jcd92 just add a new release 0.5. Can you please confirm if the issue's fixed ?

**Comment by jcd92** [comment]
Hi,
yes, just tested it and it works great now, thanks!
