### ISSUE TITLE
Question regarding the minimal python version to support

### ISSUE THREAD

**Issue by Rafiot** [mrf345/flask_datepicker#5]
I see you're using `FileNotFoundError` which is new in python 3.3. so I'm assuming you purposefully don't support anything older than that (and I support you there :) )

What is the oldest version of python you want to support? I wanted to do a few changes in the local Jquery UI sourcecode files, and was wondering if you're cool with me using pathlib for that: https://docs.python.org/3/library/pathlib.html
Which has been added in python 3.4.

**Comment by mrf345** [comment]
That was not intended to be honest :) just happened not to run it with local files on py2.
Thanks for the notice. I've added `IOError` instead, when py2 is used.

py2.7 is the oldest that I've used it with, and unfortunately still have to.
For sure, my pleasure. We can add `pathlib2` as a `extras_require` for py2.

**Comment by Rafiot** [comment]
Fair enough ;)

In the meantime, I discovered the input type "date", and it does pretty much what I want it to do.

**Comment by mrf345** [comment]
Alright, thanks for the clean up :)
