### ISSUE TITLE
Button dont work in input-group.

### ISSUE THREAD

**Issue by filipeleonelbatista** [mrf345/flask_datepicker#6]
when you click on input only, works but in input form, button dont open calendar
![image](https://user-images.githubusercontent.com/20867392/41503312-9639caa4-71a6-11e8-91f9-481cd856a855.png)

```html
<div class="input-group">
          {{ form.dtInicio(required="required", class_="form-control dp") }}
          <div class="input-group-btn">
            <button class="btn btn-default">
              <i class="glyphicon glyphicon-calendar"></i>
            </button>
         </div>
        </div>
```

**Comment by mrf345** [comment]
Hi @modernfunkboss, i added javascript work around in the new release 0.9.
first update flask_datepicker `pip install -U flask_datepicker`

Example:
```jinja
 {{ datepicker.picker(id=".whatever", btnsId='.whateverBtn') }}
```
```html
<div class="input-group">
    {{ form.dtInicio(required="required", class_="form-control whatever") }}
    <div class="input-group-btn">
        <button class="btn btn-default whateverBtn">
            <i class="glyphicon glyphicon-calendar"></i>
        </button>
    </div>
</div>
```

There is practical example in [testing_example](https://github.com/mrf345/flask_datepicker/tree/master/testing_example)

**Comment by filipeleonelbatista** [comment]
It works properly I'm grateful
