### ISSUE TITLE
minDate, maxDate mismatch in datepicker

### ISSUE THREAD

**Issue by sirjayesh** [mrf345/flask_datepicker#7]
In my html I have 
"_{{ datepicker.picker(id=".dp",dateFormat='yy-mm-dd',maxDate='2019-07-03',minDate='2018-07-03',  btnsId='.btnId') }}_"
But when the page loads, I can see that the date is enabled from 2018-08-03 till 2019-08-03. 

Similarly when I set minDate = 2018-01-01 and maxDate = 2018-12-31,
the date is enabled from 2018-02-01 to 2019-01-31.

And when I set minDate = 2018-00-01 and maxDate = 2018-11-31, date is enabled from 2018-01-01 to 2018-12-31 in the form.

Seems there is some mismatch in Month counter.

**Comment by mrf345** [comment]
Hi @sirjayesh good catch, there was an issue in generating a `new Date()` in JavaScript.
I added a new release 0.11, that fix this issue. update it `pip -U flask_datepicker`
And it should work.

**Comment by sirjayesh** [comment]
@mrf345 , updated the package to version 0.11, now it works like a charm ! 
Thanks.
Closing the issue.
