### ISSUE TITLE
Filtering data on a Flask app via a calendar

### ISSUE THREAD

**Issue by bbartling** [mrf345/flask_datepicker#9]
Hello,

I apologize if creating an issue is not the correct path for researching... But I was curious if I could use this to filter data?

For example, I have an app that can create some charts where the user first imports a CSV file containing numerical time series data via the browser. And a cool feature would be to able to filter the dataset based on some calendar dates selectable from the front end.

For example something bare bones the app user via the browser clicks a button to browse for a CSV file on this route:

```
@app.route('/transform', methods=["POST"])
def transform_view():

    f = request.files['data_file']
    filename = secure_filename(f.filename)
    f.save(filename)

    df = pd.read_csv(filename, index_col='Date', parse_dates=True)
```

And then could I use a calendar feature to filter the data? The idea that I have in mind would like a generic weekly calendar where the person could select specific time periods, like every week 1PM-5PM filter out all other data...

This maybe a bad example, but a weekly schedule like this.. Where the user could select times.
![image](https://user-images.githubusercontent.com/29737117/90049220-1e523600-dc9a-11ea-9934-dbe57e9ed181.png)

Hopefully this makes sense! Or would you have any other tips for other calendar features creations for Flask?

Thank you!
Ben

**Comment by mrf345** [comment]
Hello Ben,

No worries, happy to help!

Although I'm not sure if I understand the use-case thoroughly, you are trying to filter the data currently shown on the frontend whenever the selected date range changes?

If so, You'll need to listen to the `change` event of the input element you've assigned the datepciker to, and then add a call to the backend to do the filtering and return the filtered data. 

- You should first allow your backend endpoint to take a date range:

```python
# Note: I'm using URL parameters here to pass the start and end date you can use the POST data fields instead.

@app.route('/transform', methods=['POST'], defaults={'start': None, 'end': None})
@app.route('/transform/<start>/<end>', methods=["POST"])
def transform_view(start=None, end=None):
    ....
    df = pd.read_csv(filename, index_col='Date', parse_dates=True)

    # Then you will do the filtering according to your requirements
    if end and start:
        filtered_df = df.loc[(df['Date'] > start) & (df['Date'] < end)]
```

- From the frontend, you'll have to attach the listeners to the pickers and then fetch your data to the backend endpoint. For example:
 
```jinja2
{% extends 'bootstrap/base.html' %}
{% block scripts %}
  {{ super() }}
  {{ datepicker.loader() }} {# to load jQuery-ui #}
  {{ datepicker.picker(id="#startdate") }}
  {{ datepicker.picker(id="#enddate") }}
  <script>
    $('#startdate, #enddate').change(function(event) {
      const startDate = $('#startdate').datepicker('getDate')?.toISOString()?.slice(0,10)
      const endDate = $('#enddate').datepicker('getDate')?.toISOString()?.slice(0,10)

      // Let's confirm both datepickers aren't empty
      if (startDate && endDate) {
         // Then you will call the backend backend endpoint
         $.post(`/transform/${startDate}/${endDate}`, ... )
      }
    })
 </script>
{% endblock %}
{% block content %}
  <form id="calandar">
    <input type="text" id="startdate" />
    <input type="text" id="enddate" />
  </form>
{% endblock %}
```

Hope this helps you. Please let me know if I missed any points.
